# https://tfsec.dev/docs/github-action/
# https://github.com/aquasecurity/tfsec-sarif-action
name: tfsec-code-scanning
on:
  push:
    branches:
      - main
jobs:
  tfsec:
    timeout-minutes: 30
    name: tfsec sarif report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tfsec
        uses: tfsec/tfsec-sarif-action@v0.0.6
        with:
          sarif_file: tfsec.sarif          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif         
